version: '3.3'

services:
  mongo:
    image: mongo
    volumes:
      - $HOME/data:/data/db
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: "exit 0"

  app:
    image: pet-project-service
    container_name: pet-project-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    healthcheck:
      test: "exit 0"
