com:
  ckno:
    external:
      pokeapi:
        url: ${POKEAPI_URL:localhost}

sentry:
  environment: ${ENV:local}
  dsn: ${SENTRY_DSN:https://7e7aad618ed246d3a972ae2593c3834a@o325857.ingest.sentry.io/1832401}
  stacktrace:
    app:
      packages: com.ckno.petproject

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: pet-project
