spring:
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    username: root
    password:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  data:
    mongodb:
      uri: ${MONGODB_IGP_URI}

com:
  ckno:
    igp-front-url: ${IGP_FRONT_URL:localhost:8080}