spring:
  datasource:
    url: jdbc:mysql://b54bbba3618942:17edcb2d@eu-cdbr-west-02.cleardb.net/heroku_2f6a25e2e637ca3?reconnect=true

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect