spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_user?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect